name: Update Stargazers

on:
  schedule:
    - cron: "0 0 * * *"  # Täglich um Mitternacht
  workflow_dispatch:

jobs:
  update-stargazers:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install -g github-script@v6
          npm cache verify

      - name: Set Git config for macOS
        run: |
          git config --global core.autocrlf input
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Update Stargazers list
        uses: actions/github-script@v6
        env:
          LANG: en_US.UTF-8
          TZ: Europe/Berlin
        with:
          script: |
            const { repo, owner } = context.repo;
            
            try {
              const stargazers = await github.paginate(
                github.rest.activity.listStargazersForRepo,
                { owner, repo }
              );
              
              const stargazersList = stargazers.map(user => ({
                login: user.login,
                avatar_url: user.avatar_url,
                html_url: user.html_url
              }));
              
              const date = new Date().toLocaleString('de-DE', { 
                timeZone: 'Europe/Berlin',
                year: 'numeric',
                month: '2-digit',
                day: '2-digit',
                hour: '2-digit',
                minute: '2-digit'
              });
              
              const content = `# ⭐ Stargazers\n
## Wahlergebnisse Visualisierung
[![macOS](https://img.shields.io/badge/macOS-000000?style=for-the-badge&logo=apple&logoColor=white)](https://www.apple.com/macos)
[![Python](https://img.shields.io/badge/python-3.11+-blue.svg?style=for-the-badge&logo=python&logoColor=white)](https://www.python.org)
[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg?style=for-the-badge)](https://opensource.org/licenses/MIT)

Thanks to all our stargazers! ✨\n\n${
                stargazersList.map(user => (
                  `[![${user.login}](${user.avatar_url}&s=64)](${user.html_url})`
                )).join(' ')
              }\n\nLast updated: ${date} (Europe/Berlin)\n`;
              
              await github.rest.repos.createOrUpdateFileContents({
                owner,
                repo,
                path: 'STARGAZERS.md',
                message: `Update Stargazers list (${date})`,
                content: Buffer.from(content).toString('base64'),
                committer: {
                  name: 'GitHub Action',
                  email: 'action@github.com'
                },
                author: {
                  name: 'GitHub Action',
                  email: 'action@github.com'
                }
              });
              
              console.log('Successfully updated stargazers list');
            } catch (error) {
              console.error('Error updating stargazers list:', error);
              process.exit(1);
            }

      - name: Cleanup
        if: always()
        run: |
          npm cache clean --force
          rm -rf node_modules
